version: "3.4"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgresvolume:/var/lib/postgresql/data
    restart: always

  # mongo:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongodbvolume:/data/db

  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redisvolume:/data
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes

  # backend:
  #   build: Backend
  #   ports:
  #     - 32112:32112
  #   volumes:
  #     - ./Backend:/usr/src/app
  #   links:
  #       # - mongo
  #       # - redis
  #       - postgres

volumes:
  postgresvolume:
  # mongodbvolume:
  # redisvolume:
  
